import { z } from "zod"

// Only exact shipped native literals become diagnostic codes. No native text is published.
const messages: Readonly<Record<string, string>> = Object.freeze({
  "Offline native path invalid": "RAYA_OFFLINE_NATIVE_PATH_INVALID",
  "Offline canonical path unavailable": "RAYA_OFFLINE_CANONICAL_PATH_UNAVAILABLE",
  "Offline native path unavailable": "RAYA_OFFLINE_NATIVE_PATH_UNAVAILABLE",
  "Offline SID serialization failed": "RAYA_OFFLINE_SID_SERIALIZATION_FAILED",
  "Offline SQLite root is a directory": "RAYA_OFFLINE_SQLITE_ROOT_IS_A_DIRECTORY",
  "Offline ancestor count exceeded bound": "RAYA_OFFLINE_ANCESTOR_COUNT_EXCEEDED_BOUND",
  "Offline ancestor rename/reparse admission refused": "RAYA_OFFLINE_ANCESTOR_RENAME_REPARSE_ADMISSION_REFUSED",
  "Offline authenticated journal refused": "RAYA_OFFLINE_AUTHENTICATED_JOURNAL_REFUSED",
  "Offline backup restoration handle refused": "RAYA_OFFLINE_BACKUP_RESTORATION_HANDLE_REFUSED",
  "Offline canonical source changed": "RAYA_OFFLINE_CANONICAL_SOURCE_CHANGED",
  "Offline control canonical path differs": "RAYA_OFFLINE_CONTROL_CANONICAL_PATH_DIFFERS",
  "Offline control pipe closed before release": "RAYA_OFFLINE_CONTROL_PIPE_CLOSED_BEFORE_RELEASE",
  "Offline control branch changed before pinning": "RAYA_OFFLINE_CONTROL_BRANCH_CHANGED_BEFORE_PINNING",
  "Offline control branch changed while held": "RAYA_OFFLINE_CONTROL_BRANCH_CHANGED_WHILE_HELD",
  "Offline current SID unavailable": "RAYA_OFFLINE_CURRENT_SID_UNAVAILABLE",
  "Offline data denial construction failed": "RAYA_OFFLINE_DATA_DENIAL_CONSTRUCTION_FAILED",
  "Offline dedicated guardian launch failed": "RAYA_OFFLINE_DEDICATED_GUARDIAN_LAUNCH_FAILED",
  "Offline exact DACL restoration differs": "RAYA_OFFLINE_EXACT_DACL_RESTORATION_DIFFERS",
  "Offline exact caller parent differs": "RAYA_OFFLINE_EXACT_CALLER_PARENT_DIFFERS",
  "Offline exclusive source handle refused": "RAYA_OFFLINE_EXCLUSIVE_SOURCE_HANDLE_REFUSED",
  "Offline generation reused": "RAYA_OFFLINE_GENERATION_REUSED",
  "Offline guardian exact inherited handles refused": "RAYA_OFFLINE_GUARDIAN_EXACT_INHERITED_HANDLES_REFUSED",
  "Offline guardian exact native exit unavailable": "RAYA_OFFLINE_GUARDIAN_EXACT_NATIVE_EXIT_UNAVAILABLE",
  "Offline guardian handle-list size invalid": "RAYA_OFFLINE_GUARDIAN_HANDLE_LIST_SIZE_INVALID",
  "Offline guardian handle-list unavailable": "RAYA_OFFLINE_GUARDIAN_HANDLE_LIST_UNAVAILABLE",
  "Offline guardian initialization incomplete": "RAYA_OFFLINE_GUARDIAN_INITIALIZATION_INCOMPLETE",
  "Offline guardian input inheritance refused": "RAYA_OFFLINE_GUARDIAN_INPUT_INHERITANCE_REFUSED",
  "Offline guardian pinned native relay differs": "RAYA_OFFLINE_GUARDIAN_PINNED_NATIVE_RELAY_DIFFERS",
  "Offline guardian private stdin unavailable": "RAYA_OFFLINE_GUARDIAN_PRIVATE_STDIN_UNAVAILABLE",
  "Offline guardian stderr unavailable": "RAYA_OFFLINE_GUARDIAN_STDERR_UNAVAILABLE",
  "Offline guardian stdout unavailable": "RAYA_OFFLINE_GUARDIAN_STDOUT_UNAVAILABLE",
  "Offline handle DACL update refused": "RAYA_OFFLINE_HANDLE_DACL_UPDATE_REFUSED",
  "Offline held deadline expired": "RAYA_OFFLINE_HELD_DEADLINE_EXPIRED",
  "Offline helper image path unavailable": "RAYA_OFFLINE_HELPER_IMAGE_PATH_UNAVAILABLE",
  "Offline helper image unavailable": "RAYA_OFFLINE_HELPER_IMAGE_UNAVAILABLE",
  "Offline immutable stage handle refused": "RAYA_OFFLINE_IMMUTABLE_STAGE_HANDLE_REFUSED",
  "Offline immutable stage sharing refused": "RAYA_OFFLINE_IMMUTABLE_STAGE_SHARING_REFUSED",
  "Offline immutable stage access refused": "RAYA_OFFLINE_IMMUTABLE_STAGE_ACCESS_REFUSED",
  "Offline immutable stage missing refused": "RAYA_OFFLINE_IMMUTABLE_STAGE_MISSING_REFUSED",
  "Offline immutable stage resources refused": "RAYA_OFFLINE_IMMUTABLE_STAGE_RESOURCES_REFUSED",
  "Offline input trailing data": "RAYA_OFFLINE_INPUT_TRAILING_DATA",
  "Offline journal atomic publication refused": "RAYA_OFFLINE_JOURNAL_ATOMIC_PUBLICATION_REFUSED",
  "Offline journal field exceeded bound": "RAYA_OFFLINE_JOURNAL_FIELD_EXCEEDED_BOUND",
  "Offline journal metadata exceeded bound": "RAYA_OFFLINE_JOURNAL_METADATA_EXCEEDED_BOUND",
  "Offline journal output refused": "RAYA_OFFLINE_JOURNAL_OUTPUT_REFUSED",
  "Offline journal persistence failed": "RAYA_OFFLINE_JOURNAL_PERSISTENCE_FAILED",
  "Offline launcher exact caller differs": "RAYA_OFFLINE_LAUNCHER_EXACT_CALLER_DIFFERS",
  "Offline launcher protocol invalid": "RAYA_OFFLINE_LAUNCHER_PROTOCOL_INVALID",
  "Offline limits invalid": "RAYA_OFFLINE_LIMITS_INVALID",
  "Offline namespace data denial refused": "RAYA_OFFLINE_NAMESPACE_DATA_DENIAL_REFUSED",
  "Offline negative namespace input invalid": "RAYA_OFFLINE_NEGATIVE_NAMESPACE_INPUT_INVALID",
  "Offline negative namespace is not a directory": "RAYA_OFFLINE_NEGATIVE_NAMESPACE_IS_NOT_A_DIRECTORY",
  "Offline negative path escapes namespace": "RAYA_OFFLINE_NEGATIVE_PATH_ESCAPES_NAMESPACE",
  "Offline negative path appeared or is uncertain": "RAYA_OFFLINE_NEGATIVE_PATH_APPEARED_OR_IS_UNCERTAIN",
  "Offline operation invalid": "RAYA_OFFLINE_OPERATION_INVALID",
  "Offline original ACE preservation failed": "RAYA_OFFLINE_ORIGINAL_ACE_PRESERVATION_FAILED",
  "Offline original DACL invalid": "RAYA_OFFLINE_ORIGINAL_DACL_INVALID",
  "Offline original security descriptor invalid": "RAYA_OFFLINE_ORIGINAL_SECURITY_DESCRIPTOR_INVALID",
  "Offline pinned source read failed": "RAYA_OFFLINE_PINNED_SOURCE_READ_FAILED",
  "Offline previous guardian death uncertain": "RAYA_OFFLINE_PREVIOUS_GUARDIAN_DEATH_UNCERTAIN",
  "Offline previous guardian remains live": "RAYA_OFFLINE_PREVIOUS_GUARDIAN_REMAINS_LIVE",
  "Offline private control is not a directory": "RAYA_OFFLINE_PRIVATE_CONTROL_IS_NOT_A_DIRECTORY",
  "Offline private control overlaps selected namespace": "RAYA_OFFLINE_PRIVATE_CONTROL_OVERLAPS_SELECTED_NAMESPACE",
  "Offline private registry input trailing data": "RAYA_OFFLINE_PRIVATE_REGISTRY_INPUT_TRAILING_DATA",
  "Offline private stage output refused": "RAYA_OFFLINE_PRIVATE_STAGE_OUTPUT_REFUSED",
  "Offline protocol version invalid": "RAYA_OFFLINE_PROTOCOL_VERSION_INVALID",
  "Offline raw image contains an unrecorded object": "RAYA_OFFLINE_RAW_IMAGE_CONTAINS_AN_UNRECORDED_OBJECT",
  "Offline recovery count exceeded bound": "RAYA_OFFLINE_RECOVERY_COUNT_EXCEEDED_BOUND",
  "Offline recovery input trailing data": "RAYA_OFFLINE_RECOVERY_INPUT_TRAILING_DATA",
  "Offline recovery journal identity refused": "RAYA_OFFLINE_RECOVERY_JOURNAL_IDENTITY_REFUSED",
  "Offline recovery journal incomplete": "RAYA_OFFLINE_RECOVERY_JOURNAL_INCOMPLETE",
  "Offline recovery journal version differs": "RAYA_OFFLINE_RECOVERY_JOURNAL_VERSION_DIFFERS",
  "Offline recovery phase differs": "RAYA_OFFLINE_RECOVERY_PHASE_DIFFERS",
  "Offline recovery selected object was replaced": "RAYA_OFFLINE_RECOVERY_SELECTED_OBJECT_WAS_REPLACED",
  "Offline recovery trailing data": "RAYA_OFFLINE_RECOVERY_TRAILING_DATA",
  "Offline release identity differs": "RAYA_OFFLINE_RELEASE_IDENTITY_DIFFERS",
  "Offline rollback encountered a retained failure": "RAYA_OFFLINE_ROLLBACK_ENCOUNTERED_A_RETAINED_FAILURE",
  "Offline rollback remains uncertain; journal retained": "RAYA_OFFLINE_ROLLBACK_REMAINS_UNCERTAIN_JOURNAL_RETAINED",
  "Offline root kind invalid": "RAYA_OFFLINE_ROOT_KIND_INVALID",
  "Offline security descriptor serialization failed": "RAYA_OFFLINE_SECURITY_DESCRIPTOR_SERIALIZATION_FAILED",
  "Offline security descriptor unavailable": "RAYA_OFFLINE_SECURITY_DESCRIPTOR_UNAVAILABLE",
  "Offline selected root absent/reparse": "RAYA_OFFLINE_SELECTED_ROOT_ABSENT_REPARSE",
  "Offline selected root changed": "RAYA_OFFLINE_SELECTED_ROOT_CHANGED",
  "Offline source DACL absent": "RAYA_OFFLINE_SOURCE_DACL_ABSENT",
  "Offline source DACL decode failed": "RAYA_OFFLINE_SOURCE_DACL_DECODE_FAILED",
  "Offline source hardlink refused": "RAYA_OFFLINE_SOURCE_HARDLINK_REFUSED",
  "Offline source identity/security changed while held": "RAYA_OFFLINE_SOURCE_IDENTITY_SECURITY_CHANGED_WHILE_HELD",
  "Offline source reparse/identity refused": "RAYA_OFFLINE_SOURCE_REPARSE_IDENTITY_REFUSED",
  "Offline source seek failed": "RAYA_OFFLINE_SOURCE_SEEK_FAILED",
  "Offline stage byte limit exceeded": "RAYA_OFFLINE_STAGE_BYTE_LIMIT_EXCEEDED",
  "Offline stage size/flush differs": "RAYA_OFFLINE_STAGE_SIZE_FLUSH_DIFFERS",
  "Offline stage timestamp publication refused": "RAYA_OFFLINE_STAGE_TIMESTAMP_PUBLICATION_REFUSED",
  "Offline stage timestamp differs": "RAYA_OFFLINE_STAGE_TIMESTAMP_DIFFERS",
  "Offline stage writer close refused": "RAYA_OFFLINE_STAGE_WRITER_CLOSE_REFUSED",
  "Offline stage write failed": "RAYA_OFFLINE_STAGE_WRITE_FAILED",
  "Offline staged bytes differ from pinned source": "RAYA_OFFLINE_STAGED_BYTES_DIFFER_FROM_PINNED_SOURCE",
  "Offline token SID bound invalid": "RAYA_OFFLINE_TOKEN_SID_BOUND_INVALID",
  "Offline token SID unavailable": "RAYA_OFFLINE_TOKEN_SID_UNAVAILABLE",
  "Offline tree count exceeded bound": "RAYA_OFFLINE_TREE_COUNT_EXCEEDED_BOUND",
  "Offline directory inventory exceeded bound": "RAYA_OFFLINE_DIRECTORY_INVENTORY_EXCEEDED_BOUND",
  "Offline directory depth exceeded bound": "RAYA_OFFLINE_DIRECTORY_DEPTH_EXCEEDED_BOUND",
  "Offline wrapped frame exceeded bound": "RAYA_OFFLINE_WRAPPED_FRAME_EXCEEDED_BOUND",
})
export const codes = Object.freeze([
  ...Object.values(messages),
  "RAYA_OFFLINE_FRAME_INVALID",
  "RAYA_OFFLINE_UNKNOWN_REFUSAL",
  "RAYA_OFFLINE_ROLLBACK_UNCONFIRMED",
  "RAYA_OFFLINE_EARLY_RETIREMENT",
])
const retired = z
  .object({
    version: z.union([z.literal(1), z.literal(2), z.literal(3), z.literal(4)]),
    generation: z.string().uuid(),
    state: z.literal("retired"),
    restored: z.boolean(),
    failures: z.array(z.string().max(1024)).max(128),
    portableCaptureAuthorized: z.literal(false),
  })
  .strict()
function error(code: string) {
  return Object.assign(new Error("Native offline preparation refused"), { code })
}
/** An early terminal response is failure even after confirmed rollback; it never grants an image. */
export function preparation(raw: unknown, generation: string, version: 1 | 2 | 3 | 4 = 1): unknown {
  if (typeof raw !== "object" || raw === null || !("state" in raw) || raw.state !== "retired") return raw
  const result = retired.safeParse(raw)
  if (!result.success || result.data.generation !== generation || result.data.version !== version)
    throw error("RAYA_OFFLINE_FRAME_INVALID")
  const failures = result.data.failures.map((message) =>
    error(Object.hasOwn(messages, message) ? messages[message] : "RAYA_OFFLINE_UNKNOWN_REFUSAL"),
  )
  if (!result.data.restored) failures.push(error("RAYA_OFFLINE_ROLLBACK_UNCONFIRMED"))
  if (!failures.length) failures.push(error("RAYA_OFFLINE_EARLY_RETIREMENT"))
  throw new AggregateError(failures, "Native offline preparation refused")
}
