import AxeBuilder from "@axe-core/playwright"
import { expect, test } from "@playwright/test"

for (const scheme of ["light", "dark"])
  for (const width of [320, 760])
    test(`web action semantics in ${scheme} at ${width}px`, async ({ page }, info) => {
      await page.setViewportSize({ width, height: 720 })
      await page.goto(`/?scheme=${scheme}`)
      const primary = page.getByRole("button", { name: "Primary", exact: true })
      const secondary = page.getByRole("button", { name: "Secondary", exact: true })
      const quiet = page.getByRole("button", { name: "Quiet", exact: true })
      const destructive = page.getByRole("button", { name: "Delete translated configuration permanently" }).first()
      await expect(primary).toHaveAttribute("data-intent", "primary")
      await expect(primary).toHaveAttribute("data-variant", "primary")
      await expect(primary).toHaveAttribute("data-size", "sm")
      await expect(secondary).toHaveAttribute("data-intent", "secondary")
      await expect(secondary).toHaveAttribute("data-variant", "secondary")
      await expect(secondary).toHaveAttribute("data-size", "default")
      await expect(quiet).toHaveAttribute("data-intent", "quiet")
      await expect(quiet).toHaveAttribute("data-variant", "ghost")
      await expect(quiet).toHaveAttribute("data-size", "lg")
      await expect(destructive).toHaveAttribute("data-intent", "destructive")
      await expect(destructive).toHaveAttribute("data-variant", "destructive")
      const trigger = page.getByRole("button", { name: "Review deletion" })
      await trigger.click()
      const dialog = page.getByRole("alertdialog")
      const cancel = dialog.getByRole("button", { name: "Keep existing configuration" })
      const confirm = dialog.getByRole("button", { name: "Delete translated configuration permanently" })
      await expect(cancel).toBeFocused()
      await expect(confirm).toHaveAttribute("data-intent", "destructive")
      await page.keyboard.press("Escape")
      await expect(dialog).toHaveCount(0)
      await expect(trigger).toBeFocused()
      await trigger.click()
      await expect(cancel).toBeFocused()
      await confirm.click()
      await expect(confirm).toBeDisabled()
      await expect(confirm).toHaveAttribute("aria-busy", "true")
      await expect(confirm).toHaveAttribute("data-pending", "true")
      await expect(page.getByRole("alert")).toContainText("Your saved provider remains available")
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
      await page.screenshot({ path: info.outputPath("web-action-semantics.png"), fullPage: true })
      const audit = await new AxeBuilder({ page }).include("main").withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze()
      expect(audit.violations).toEqual([])
    })
