import AxeBuilder from "@axe-core/playwright"
import { expect, test } from "@playwright/test"

for (const theme of ["light", "dark", "contrast"])
  for (const width of [320, 460]) {
    test(`${theme} destructive controls at ${width}px`, async ({ page }, info) => {
      const errors: string[] = []
      page.on("pageerror", (error) => errors.push(error.message))
      await page.setViewportSize({ width, height: 760 })
      if (theme === "contrast") await page.emulateMedia({ forcedColors: "active" })
      await page.goto(`/?theme=${theme}`)
      const plain = page.getByTestId("default")
      await expect(plain).toHaveAttribute("data-variant", "secondary")
      await expect(plain).toHaveAttribute("type", "button")
      for (const variant of ["primary", "secondary", "ghost"]) {
        const button = page.getByRole("button", { name: new RegExp(`^${variant}$`, "i") })
        await expect(button).toHaveAttribute("data-variant", variant)
        await expect(button).not.toHaveAttribute("data-intent", "destructive")
      }
      await plain.click()
      await expect(page.locator("[data-submits]")).toHaveText("0")
      await page.getByRole("button", { name: "Submit form" }).click()
      await expect(page.locator("[data-submits]")).toHaveText("1")
      const action = page.getByTestId("reactive")
      await expect(action).toBeDisabled()
      expect(await action.evaluate((node) => node instanceof HTMLButtonElement && node.disabled)).toBe(true)
      await action.evaluate((node) => (node as HTMLButtonElement).click())
      await expect(page.locator("[data-actions]")).toHaveText("0")
      await page.getByRole("button", { name: "Toggle disabled" }).click()
      await expect(action).toBeEnabled()
      await expect(action).toHaveAttribute("data-intent", "destructive")
      await action.focus()
      await page.keyboard.press("Enter")
      await expect(page.locator("[data-actions]")).toHaveText("1")
      await page.keyboard.press("Space")
      await expect(page.locator("[data-actions]")).toHaveText("2")
      await page.getByRole("button", { name: "Toggle variant" }).click()
      await expect(action).toHaveAttribute("data-variant", "primary")
      await expect(action).not.toHaveAttribute("data-intent", "destructive")
      await page.getByRole("button", { name: "Toggle variant" }).click()
      await expect(action).toHaveAttribute("data-intent", "destructive")
      const trigger = page.getByRole("button", { name: "Review removal" })
      await trigger.click()
      const dialog = page.getByRole("dialog")
      const cancel = dialog.getByRole("button", { name: "Cancel", exact: true })
      const remove = dialog.getByRole("button", { name: "Remove", exact: true })
      await expect(cancel).toBeFocused()
      await expect(remove).toHaveAttribute("data-intent", "destructive")
      await page.screenshot({ path: info.outputPath("destructive-initial-focus.png"), fullPage: true })
      await page.keyboard.press("Escape")
      await expect(dialog).toHaveCount(0)
      await expect(trigger).toBeFocused()
      await expect(page.locator("[data-actions]")).toHaveText("2")
      await trigger.click()
      await expect(cancel).toBeFocused()
      await page.keyboard.press("Enter")
      await expect(dialog).toHaveCount(0)
      await expect(page.locator("[data-actions]")).toHaveText("2")
      for (const [key, count] of [
        ["Enter", "3"],
        ["Space", "4"],
      ]) {
        await trigger.click()
        await expect(cancel).toBeFocused()
        await remove.focus()
        await page.keyboard.press(key!)
        await expect(dialog).toHaveCount(0)
        await expect(page.locator("[data-actions]")).toHaveText(count!)
      }
      await trigger.focus()
      await page.keyboard.press("Enter")
      await expect(cancel).toBeFocused()
      expect(await dialog.evaluate((node) => node.scrollWidth <= node.clientWidth)).toBe(true)
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
      expect(
        await cancel.evaluate((node) => {
          const style = getComputedStyle(node)
          return (style.outlineStyle !== "none" && parseFloat(style.outlineWidth) > 0) || style.boxShadow !== "none"
        }),
      ).toBe(true)
      await page.screenshot({ path: info.outputPath("destructive-confirmation.png"), fullPage: true })
      const audit = await new AxeBuilder({ page })
        .include('[role="dialog"]')
        .withTags(["wcag2a", "wcag2aa", "wcag21aa"])
        .analyze()
      expect(audit.violations).toEqual([])
      expect(errors).toEqual([])
    })
  }

test("dialog focus ownership survives nested, replacement and detached openers", async ({ page }) => {
  await page.goto("/?theme=dark")
  const trigger = page.getByRole("button", { name: "Review nested" })
  await trigger.click()
  const inner = page.getByRole("button", { name: "Review inner" })
  await expect(inner).toBeFocused()
  await inner.press("Enter")
  await expect(page.getByRole("button", { name: "Keep inner" })).toBeFocused()
  const active = await page.locator("main").getAttribute("data-dialog-active")
  await page.keyboard.press("Escape")
  await expect(page.getByRole("dialog", { name: "Inner confirmation" })).toHaveCount(0)
  await expect(inner).toBeFocused()
  await expect(page.locator("main")).not.toHaveAttribute("data-dialog-active", active!)
  await page.keyboard.press("Escape")
  await expect(page.getByRole("dialog")).toHaveCount(0)
  await expect(trigger).toBeFocused()
  await trigger.click()
  await page.getByRole("button", { name: "Replace confirmation" }).click()
  await expect(page.getByRole("button", { name: "Keep replacement" })).toBeFocused()
  await expect(page.getByRole("dialog", { name: "Outer confirmation" })).toHaveCount(0)
  await page.keyboard.press("Escape")
  await expect(page.getByRole("dialog")).toHaveCount(0)
  await expect(trigger).not.toBeFocused()
  await trigger.click()
  await page.getByRole("button", { name: "Detach opener" }).click()
  await expect(trigger).toHaveCount(0)
  await page.keyboard.press("Escape")
  await expect(page.getByRole("dialog")).toHaveCount(0)
  expect(await page.evaluate(() => document.activeElement === document.body)).toBe(true)
})

test("long localized confirmation labels stay usable at 320px", async ({ page }, info) => {
  await page.setViewportSize({ width: 320, height: 760 })
  await page.goto("/?theme=light")
  await page.getByRole("button", { name: "Review long labels" }).click()
  const dialog = page.getByRole("dialog")
  await expect(dialog.getByRole("button", { name: "Vorhandene Konfiguration beibehalten" })).toBeFocused()
  expect(await dialog.evaluate((node) => node.scrollWidth <= node.clientWidth)).toBe(true)
  for (const button of await dialog.getByRole("button").all()) {
    const bounds = await button.boundingBox()
    expect(bounds).not.toBeNull()
    expect(bounds!.x).toBeGreaterThanOrEqual(0)
    expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(320)
  }
  await page.screenshot({ path: info.outputPath("destructive-long-labels.png"), fullPage: true })
})

test("caller autofocus cancellation and owner disposal retain focus ownership", async ({ page }) => {
  await page.goto("/?theme=dark")
  await page.getByRole("button", { name: "Review caller focus" }).click()
  await expect(page.getByRole("button", { name: "Keep caller" })).toBeFocused()
  await page.keyboard.press("Escape")
  await expect(page.getByRole("dialog")).toHaveCount(0)
  await expect(page.getByTestId("default")).toBeFocused()
  const boundary = page.getByRole("button", { name: "Review owner boundary" })
  await boundary.click()
  await expect(page.getByRole("button", { name: "Keep outer owner" })).toBeFocused()
  await page.getByRole("button", { name: "Review owned dialog" }).click()
  await expect(page.getByRole("button", { name: "Unmount owner" })).toBeVisible()
  await page.getByRole("button", { name: "Unmount owner" }).click()
  await expect(page.getByRole("dialog", { name: "Owned confirmation" })).toHaveCount(0)
  await expect(page.getByRole("button", { name: "Review owned dialog" })).toHaveCount(0)
  await expect(page.getByRole("dialog", { name: "Owner boundary" })).toBeVisible()
  await page.keyboard.press("Escape")
  await expect(page.getByRole("dialog")).toHaveCount(0)
  await expect(boundary).toBeFocused()
})
