import { expect, test } from "@playwright/test"

test("Ask card sits above the composer and keeps explicit navigation", async ({ page }, info) => {
  await page.setViewportSize({ width: 683, height: 700 })
  await page.goto("/?state=dark-question")
  const card = page.locator('[data-component="question-dock"]')
  await expect(card).toBeVisible()
  await expect(card.locator('[data-slot="question-progress-count"]')).toHaveText("1 of 3")
  await expect(card.locator('[data-slot="question-option-number"]')).toHaveText(["1", "2", "3", "4"])
  const box = await card.boundingBox()
  const prompt = await page.locator(".prompt-input-container").boundingBox()
  expect(box && prompt && box.y + box.height <= prompt.y).toBeTruthy()
  await page.screenshot({ path: info.outputPath("question.png"), fullPage: true })
  await card.locator('[data-slot="question-option"]').nth(1).click()
  await expect(card.locator('[data-slot="question-progress-count"]')).toHaveText("1 of 3")
  await card.locator('[data-slot="question-next"]').click()
  await expect(card.locator('[data-slot="question-progress-count"]')).toHaveText("2 of 3")
  await card.getByRole("button", { name: "Previous question" }).click()
  await expect(card.locator('[data-slot="question-option"]').nth(1)).toHaveAttribute("data-picked", "true")
  await card.locator('[data-slot="question-next"]').click()
  await card.locator('[data-slot="question-option"]').first().click()
  await card.locator('[data-slot="question-next"]').click()
  await card.locator('[data-slot="question-option"]').first().click()
  await expect(card.locator('[data-slot="question-next"]')).toHaveText("Review")
  await card.locator('[data-slot="question-next"]').click()
  await expect(card.locator('[data-slot="review-title"]')).toBeVisible()
  await card.locator('[data-slot="question-next"]').click()
  await expect(page.locator("html")).toHaveAttribute("data-preview-question", /"id":"preview-question"/)
  await expect(page.locator("html")).toHaveAttribute("data-preview-question", /"Small teams"/)
  await expect(card.locator('[data-slot="question-next"]')).toBeDisabled()
})

test("history starts with three chats and View all opens a scrollable, categorized picker", async ({ page }, info) => {
  await page.setViewportSize({ width: 683, height: 800 })
  await page.goto("/?state=dark-welcome")
  await expect(page.locator(".raya-home__row")).toHaveCount(3)
  const home = await page.locator(".raya-home").boundingBox()
  const heading = await page.locator(".raya-home__heading").boundingBox()
  expect(home && heading && heading.y - home.y < 20).toBeTruthy()
  await page.getByRole("button", { name: "View all (5)" }).click()
  const picker = page.locator(".history-picker")
  await expect(picker).toBeVisible()
  await expect(picker.locator(".history-picker__row")).toHaveCount(5)
  await expect(picker.locator(".history-picker__list")).toHaveCSS("overflow-y", "auto")
  await page.screenshot({ path: info.outputPath("history-open.png"), fullPage: true })
  await picker.getByRole("searchbox", { name: "Search recent chats" }).fill("composer")
  await expect(picker.locator(".history-picker__row")).toHaveCount(1)
  await picker.getByRole("button", { name: "More options for Reskin the composer and goal bar" }).click()
  await page.getByRole("menuitem", { name: "Delete chat" }).click()
  await page.getByRole("button", { name: "Delete" }).click()
  await expect(picker.locator(".history-picker__row")).toHaveCount(0)
  await picker.getByRole("button", { name: "Close history" }).click()
  await expect(picker).toHaveCount(0)
})

test("History manages and deletes multiple chats in the new layout", async ({ page }) => {
  await page.setViewportSize({ width: 683, height: 800 })
  await page.goto("/?state=dark-history")
  await page.getByRole("button", { name: "Manage chats" }).click()
  await expect(page.locator('.history-picker[data-embedded="true"]')).toBeVisible()
  await page.getByRole("button", { name: "Select chats" }).click()
  await page.locator('.history-picker[data-embedded="true"]').getByRole("checkbox").first().check()
  await expect(page.getByRole("toolbar", { name: "Selected chats" })).toContainText("1 selected")
  await page.getByRole("button", { name: "Delete selected" }).click()
  await expect(page.getByRole("dialog", { name: "Delete selected chats?" })).toContainText("1 chats")
  await page.getByRole("button", { name: "Delete chats" }).click()
  await expect(page.getByRole("toolbar", { name: "Selected chats" })).toHaveCount(0)
})
