import AxeBuilder from "@axe-core/playwright"
import { expect, test } from "@playwright/test"

for (const theme of ["light", "dark", "contrast"])
  for (const width of [320, 760]) {
    test(`${theme} OpenAI Speech settings at ${width}px`, async ({ page }, info) => {
      const errors: string[] = []
      page.on("pageerror", (error) => errors.push(error.message))
      await page.setViewportSize({ width, height: 1000 })
      if (theme === "contrast") await page.emulateMedia({ forcedColors: "active" })
      await page.goto(`/?theme=${theme}`)
      const engine = page.getByRole("button", { name: /^Voice engine/ })
      await expect(engine).toContainText("OpenAI Realtime (preview)")
      await expect(page.getByText("gpt-realtime-2.1", { exact: true })).toBeVisible()
      await expect(page.getByRole("button", { name: "Test voice", exact: true })).toHaveCount(0)
      const key = page.getByLabel("OpenAI API key", { exact: true })
      const save = page.getByRole("button", { name: "Save OpenAI API key" })
      const clear = page.getByRole("button", { name: "Clear OpenAI API key" })
      await expect(key).toHaveAttribute("type", "password")
      await expect(save).toBeDisabled()
      await key.fill("synthetic-fixture-key")
      await key.focus()
      await page.keyboard.press("Tab")
      await expect(save).toBeFocused()
      await page.keyboard.press("Enter")
      await expect(key).toHaveValue("")
      await expect(page.getByText("An OpenAI key is stored in VS Code Secret Storage.", { exact: false })).toBeVisible()
      await expect(page.locator("[data-messages]")).toContainText('"kind":"openai","key":"synthetic-fixture-key"')
      await clear.focus()
      await page.keyboard.press("Enter")
      await expect(page.getByText("Add a key with access to the realtime model.", { exact: false })).toBeVisible()
      await expect(page.locator("[data-messages]")).toContainText('"type":"speechKeyUpdate","kind":"openai"}')
      await page.getByRole("button", { name: "Show missing-key error" }).click()
      await expect(page.getByRole("alert")).toContainText("Add your OpenAI API key")
      await expect(page.getByRole("status")).toContainText("off")
      await expect(page.locator("[data-captures]")).toHaveText("0")
      await expect(page.locator("[data-messages]")).not.toContainText('"type":"speechOpenAIStart"')
      await engine.focus()
      await page.keyboard.press("Enter")
      await expect(page.getByRole("option", { name: "OpenAI Realtime (preview)" })).toBeVisible()
      await page.keyboard.press("Escape")
      await expect(engine).toBeFocused()
      await expect(page.getByRole("alert")).toBeVisible()
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
      if (theme === "contrast") await page.emulateMedia({ forcedColors: "none" })
      const audit = await new AxeBuilder({ page })
        .include(".speech-settings")
        .withTags(["wcag2a", "wcag2aa", "wcag21aa"])
        .analyze()
      expect(audit.violations).toEqual([])
      if (theme === "contrast") await page.emulateMedia({ forcedColors: "active" })
      await page.screenshot({ path: info.outputPath("speech-settings.png"), fullPage: true })
      expect(errors).toEqual([])
    })
  }
